### ISSUE TITLE
using startTransaction will result in 411 length required

### ISSUE THREAD

**Issue by wolfmeisternl** [Evidos/signhost-phpdemoclient#16]
Adding content-length: 0 to the headers in startTransaction will resolve this:

curl_setopt($ch, CURLOPT_HTTPHEADER, array(
         "Content-Type: application/json",
         "Content-Length: 0",
         "Application: APPKey ".$this->AppKey,
         "Authorization: APIKey ".$this->ApiKey
     ));

**Comment by ATimmeh33** [comment]
Removing content-type for a bodyless PUT was more appropriate.

**Comment by jstolp** [comment]
If anyone faces this issue... try and add a header "Content-Length: 0" on the PUT /start-transaction call

**Comment by MrJoe** [comment]
> If anyone faces this issue... try and add a header "Content-Length: 0" on the PUT /start-transaction call

The better solution would be to remove the "Content-Type" header from your request instead.

**Comment by jstolp** [comment]
@MrJoe I Can't find anything in https://tools.ietf.org/html/rfc7231#section-4.3.4 could you point me to the proper RFC?

**Comment by MrJoe** [comment]
https://tools.ietf.org/html/rfc7231#section-3.1.1.5
> A sender that generates a message containing a payload body SHOULD
   generate a Content-Type header field in that message...

However you are not generating a payload so you should not include the Content-Type header. If you choose to add the Content-Type anyway you'll have to follow 3.3.2:

https://tools.ietf.org/html/rfc7230#section-3.3.2 

> A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body.  For example, a Content-Length header
   field is normally sent in a POST request even when the value is 0
   (indicating an empty payload body).

So preferably you should not include the Content-Type at all when you don't provide a payload.
